### ISSUE TITLE
Acesso de commits pra a equipe do Hub de minutas

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#1]
Por enquanto, a equipe que forma parte de este team deveria ter acceso neste repositorio. Eu tenho acesso mais o Categulario e o Oscar nao tem. Poderias me ajudar a adiciona-los neste repo, @giuliocc ?

**Comment by ogecece** [comment]
@basicavisual adicionei cada perfil individualmente agora. Podem testar se funcionou?

**Comment by basicavisual** [comment]
adiantou! obrigada
