### ISSUE TITLE
Changes to position and typography of the general announcement

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#10]
as per the mockup, certain the general site announcement uses the nexto-mono typography. Please include it for the following css classes:

omnipresent-banner-title .omnipresent-banner-short-description 

![image](https://github.com/okfn-brasil/minutas/assets/8941178/2784026f-bb69-457e-ade9-db8242a4eb8f)

Also, as per the mockup, the announcement should go after the main nav but before the hero. Here's the mockup

![image](https://github.com/okfn-brasil/minutas/assets/8941178/116e1393-72a4-4ca8-ac5e-878e570e69f2)

**Comment by ghost** [comment]
Leaving this as a reference for now:

File: [`app/views/layouts/decidim/_wrapper.html.erb`](https://github.com/decidim/decidim/blob/83be368eb17d4a1b77512dbb59ed2bff04e40246/decidim-core/app/views/layouts/decidim/_wrapper.html.erb)

```erb
<%= render partial: "layouts/decidim/omnipresent_banner" %>
```

**File**: `/app/packs/stylesheets/okbr/_hero.scss`
```css
#hero {
  background-size: contain;
  background-position: center;
  background-repeat: no-repeat;
  background-color: whitesmoke;
}
```

**File**: `/app/packs/stylesheets/okbr/_banner.scss`
```sass
.omnipresent-banner {
  background-color: $color-purple
  font-family: 'Necto mono'
  font-size: 1.0em
}
```

<hr>

<img width="1400" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/d2cc8ea2-e7bf-4960-b0a4-f77370df8331">

**Comment by ghost** [comment]
Accidentally closed the pull request.

_TIL: Pressing <kbd>&#x2318; &#x23ce;</kbd> will close a PR._ 🙈
