### ISSUE TITLE
Change style for active main-nav item

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#11]
Estilização do link ativo do menu superior pode ser diferente: usar negrito e outra cor em vez do sublinhado atual

![image](https://github.com/okfn-brasil/minutas/assets/8941178/5bc1fadf-ac2a-497f-a015-5b7b8b4cd280)

OKBR team has requested the styling of the active element to be different: bold and another color instead of underlined (more specifically it is a border-bottom element to the div) for this issue I will confirm with the OKBR team before the change is made so that we know exactly what we are changing it to

**Comment by basicavisual** [comment]
The design would be as follows (bold, color fúscia, remove border color) 
![image](https://github.com/okfn-brasil/minutas/assets/8941178/b97f8bdc-fe07-4a89-b1c4-a0c914994da7)

**Comment by ghost** [comment]
Increase `font-size` to `1.2em`

**Comment by ghost** [comment]
Screenshot from my `localhost` after the patch:

<img width="1228" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/4549d2f7-e450-4cc9-8daf-18bc43c667bc">

Decided to not increase the font as mentioned in the previous comment. It seems too big from my perspective.
