### ISSUE TITLE
Change default color of links

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#13]
Decidim uses a teal color for default, for links inside the application. It needs to be changed, however we need the color to be used. From the design itself, we can infer it is black, however before changing them we want to confirm, as black makes for low accesibility (it is not evident it is a link and not just regular text)

![image](https://github.com/okfn-brasil/minutas/assets/8941178/e4234a4b-a1f6-4977-a47f-5343a7a854d5)

**Comment by basicavisual** [comment]
Color of links must go in #6173e8

**Comment by ghost** [comment]
Closing in favor of: https://github.com/okfn-brasil/minutas/issues/16
