### ISSUE TITLE
Change color / styles of announcement elements

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#15]
Decidim has a series of announcement elements within the processes. These should be using the same style. We should change the color to better reflect the existing design. I am assigning this to myself so that we discuss with the OKBR team what color to use

![image](https://github.com/okfn-brasil/minutas/assets/8941178/84badf02-d955-44b3-b22c-0ae0d8017dfd)

**Comment by basicavisual** [comment]
The changes are as following:
- Change color to #6173e8 this is referenced as secondary color 
- Remove horizontal line on top (darker teal)
- Background is referencing secondary color at ,1 opacity, check this class:

![image](https://github.com/okfn-brasil/minutas/assets/8941178/0573deef-cee5-4079-b978-ea62301f4f98)

**Comment by ghost** [comment]
Screenshot after patch:

<img width="1440" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/8cf3f806-4729-4b5f-85c2-7b356d348a87">
