### ISSUE TITLE
Review styles of metadata rich cards 

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#16]
There's several types of cards, simpler cards (just a picture, a title and description) and metadata rich cards. This issue is for metadata-rich cards. For other cards view corresponding issue

![image](https://github.com/okfn-brasil/minutas/assets/8941178/4e123b1b-6002-4d73-aeb6-a680e5bb12f4)

1. Change card title to bold
2. Change link color from teal to fuscia
3. As for the "Criado em" needs a line-heigh a little bit higher, perhaps 1.2. Check the following class 

![image](https://github.com/okfn-brasil/minutas/assets/8941178/665f03ea-51e6-40d0-b50f-42a6e25b3d51)

![image](https://github.com/okfn-brasil/minutas/assets/8941178/78a7c4f9-62ec-4aef-8a58-97aea9168cdb)

**Comment by basicavisual** [comment]
change color from teal to #6173e8 and title must go in bold 

![image](https://github.com/okfn-brasil/minutas/assets/8941178/76495e74-a710-42b2-94b7-5fe6351fa668)

**Comment by basicavisual** [comment]
Please apply the same changes to cards on the assembly module
![image](https://github.com/okfn-brasil/minutas/assets/8941178/80d53be5-e7eb-4076-8593-89acc107c129)
https://minutas.ok.org.br/assemblies

**Comment by ghost** [comment]
Screenshot after patch:

<img width="396" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/a58d4a38-14ec-4ee0-91ad-b576bb185331">
