### ISSUE TITLE
Button style changes cascaded to participatory texts, but broke 

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#17]
In order to comply with the design, the styles of the buttons where changed to be more rounded, and a larger size of text, however this was cascaded to other parts of the application as it is natural. Check the button for participatory texts:

![image](https://github.com/okfn-brasil/minutas/assets/8941178/d6bfbe4c-c388-4a25-afbf-bb3e9ca373d7)
 
It can be viewed by hovering over any element of the text. Fix it so that it:

1. does not break
2. uses an accent color of the cominutas branding

**Comment by basicavisual** [comment]
Use the same ultramarine color as indicated in #16

**Comment by ghost** [comment]
Screenshot after patch:
<img width="278" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/8ea5b3d1-7e1f-416c-a7dd-d568d7088fff">
