### ISSUE TITLE
Images uploaded through uploaded are not viewable on the site (except for logos)

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#19]
after re-uploading hero image, it does not appear viewable. Try accessing the image here: https://minutas.ok.org.br/admin/organization/homepage/content_blocks/hero/edit or see the console after loading the landing and you get a 404 
![image](https://github.com/okfn-brasil/minutas/assets/8941178/0062e817-f9a1-4055-ba35-6fe8dbdb460b)

This is most likely to incorrect mounting of the storage module. It is also reflected in banner images for participatory processes

**Comment by ghost** [comment]
Is it possible to see the logs or how is it deployed, @basicavisual ?

I want to know which storage provider is using in production (set by the variable: `STORAGE_PROVIDER`).

**Comment by categulario** [comment]
with the kind help of @samanera I can confirm that this problem is solved.

there were two problems:

* background jobs were not properly configured
* background job container did not have the storage volume attached.
