### ISSUE TITLE
Style adjustments to help section

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#21]
Help section needs to be adjusted to the general styling. 

Secondary color must be: #6173e8

![image](https://github.com/okfn-brasil/minutas/assets/8941178/b2307c83-646b-4c2f-bdd2-a490556f3868)

1. Card title foes in secondary color and bold
2. Font must be in accordance with main main font HK Grotesk
3. Section title ("Topicos") turn into uppercases, remove border color left and switch to HK Grotesk, links on card must also go on secondary color

**Comment by ghost** [comment]
Screenshot after patch: 

<img width="416" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/71ca5966-6dc1-4fd0-b752-0975632f6fd9">
