### ISSUE TITLE
Review styles of simple cards

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#23]
This issue for for simple cards (pic, description and title) for metadata rich cards see issue #16 

In the mockup cards are simpler: 

![image](https://github.com/okfn-brasil/minutas/assets/8941178/c1550d4c-867c-4cfd-ba76-b317df969c32)

In decidim cards have more info:

![image](https://github.com/okfn-brasil/minutas/assets/8941178/431856cb-7ec5-4359-a196-6de71c797422)

You must do the following:
- remove borders and background color
- reduce space between picture and title
- remove description and / or buttons
- make title and picture clickable / linkable

**Comment by samanera** [comment]
Match card according to design. Review `card__full` design.

**Comment by ghost** [comment]
<img width="682" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/95589b7d-392e-4cbf-94f3-7fea1a05634e">

Already addressed.
