### ISSUE TITLE
Style adjustments to login section 

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#26]
We need to armonize the elements on the login page to reflect the design elements:

![image](https://github.com/okfn-brasil/minutas/assets/8941178/ddbc6ed6-9ef6-46aa-9234-b512b3a24db3)

1. Links ought to be the secondary color #6173e8
2. Text-transform to capitalize for "Iniciar sessão"
3. Button must reflect the design pattern of being rounded, with the wording in a bigger font, bold, capitalized

**Comment by ghost** [comment]
Closed with the following commit: https://github.com/okfn-brasil/minutas/commit/9d8b866663b2951949bf8e86accdf13e066267ae

<img width="400" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/3e72ad4f-346c-4b15-93d0-065480003c7f">
