### ISSUE TITLE
Credenciais SMTP

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#3]
Para poder enviar emails o decidim precisa credenciais de algum serviço SMTP

Username
Password
SMTP server
SMTP Port

é possível fazer pelo painel /system

**Comment by ogecece** [comment]
@basicavisual podemos utilizar um serviço como Mailjet ou AWS SES?

**Comment by categulario** [comment]
sim, é possível usar os serviços que você mencionou

**Comment by ogecece** [comment]
@categulario do you have any preferences?

Here we use both services but if there is any you are more comfortable to integrate and reasonably priced we could configure it

**Comment by categulario** [comment]
From the ones you mentioned I have no preference. Any of them would work just fine.

**Comment by basicavisual** [comment]
This has been solved!
