### ISSUE TITLE
Aceitar instalação de package no repo de CI

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#4]
Para implementar o processo de continuous integration, por favor de aceitar a instalação do pacote minutas/decidim que se encontra neste URL: https://github.com/orgs/okfn-brasil/packages/container/package/minutas%2Fdecidim

Ele contem a imagen de docker que estariamos a utilizar

**Comment by ogecece** [comment]
Pacote configurado para github actions deste repo e permissões de escrita também foram dadas a vocês. Pode testar se tá tudo certinha @basicavisual ?

**Comment by categulario** [comment]
Almost ready. Can you make the package public? Right now it is marked as internal. While this is not strictly necessary it does simplify the deployment because public packages don't require an access token to be pulled and since the repository is public itself it just makes sense.

Muito obrigado!

**Comment by basicavisual** [comment]
cc @giuliocc pode revisar o comentário do categulario? ainda não acordamos a linguagem para issues. o ingles esta bem? ou prefere espanhol ou português?

**Comment by ogecece** [comment]
@categulario Done!

@basicavisual em outros projetos temos priorizado o português e caso não seja possível a pessoa escreve no idioma que se sentir mais confortável. Podemos fazer assim?

**Comment by basicavisual** [comment]
podemos sim :) eu continuo em português y @categulario continua assim em inglés (a menos que vc prefera espanhol). Abraço!

**Comment by categulario** [comment]
One last step (I swear this is the last one). In the repository settings there's an "Actions" tab and inside it a "Workflow permissions" section. Can you enable "Read and write permissions"? This is so that the container image can be published automatically from the github actions.

![imagen](https://i.stack.imgur.com/2wLaU.png)

**Comment by basicavisual** [comment]
cc @giuliocc

**Comment by ogecece** [comment]
@categulario sorry for the delay. Didn't see the notification.

This permission was actually enabled :thinking:

Do you want me to give you admin permissions temporarily if its not working yet?

**Comment by categulario** [comment]
sure, just to debug the automatic image publication from sources

**Comment by ogecece** [comment]
@categulario done!

**Comment by categulario** [comment]
Awesome, the image publication pipeline from source is fully set up. It is enough to create a git tag (for example `1.2.3`) and push it, and a corresponding container image will be created at `ghcr.io/okfn-brasil/minutas/decidim:1.2.3`.

**Comment by ogecece** [comment]
Perfect! I'll revert the admin permissions then
