### ISSUE TITLE
Server at top capacity already

### ISSUE THREAD

**Issue by categulario** [okfn-brasil/minutas#7]
![Captura desde 2023-07-10 11-23-33](https://github.com/okfn-brasil/minutas/assets/790756/99b4e569-e83b-4114-8158-2154fa46bf23)

It might be a good idea (in preparation for going to production) to double or even mutiply by 4 the amount of RAM and add more processors. 4 Gb might be enough for a low load and 8 Gb for peaks and heavier usage.

**Comment by categulario** [comment]
Disclaimer: Those numbers are affected by a deployment being run (see PID 1122330 with command `/usr/bin/python3 ...`). Normal RAM usage was seen at 750 Mb when the deployment finished, however we'll need some margin for operations like these to run smoothly.

**Comment by basicavisual** [comment]
an good digital ocean size is this:

![image](https://github.com/okfn-brasil/minutas/assets/8941178/dcca967a-4711-4b11-8cf2-72de28dec269)

**Comment by ogecece** [comment]
Upgraded to 2GB RAM

If it's not enough we can reopen this issue @categulario @basicavisual
