### ISSUE TITLE
Menus no in agreement with initial design

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#9]
"Menus ainda em desacordo com o design inicial (deixar todos ao lado da logo, a barra de busca vem depois de todos os links)"
"Menus are still not reflecting the initial design (have all menu items beside the logo, search bar comes after links)"
OKBR's original proposal:
![image](https://github.com/okfn-brasil/minutas/assets/8941178/7f38b87f-eed7-4cd5-aefb-e09b2a2fa87f)

Codeando's implementation: 
![image](https://github.com/okfn-brasil/minutas/assets/8941178/0c14cfdb-1def-4959-b978-f0db5d3f9e08)

**Comment by basicavisual** [comment]
For this specific issue, I asked @categulario to keep the order as he did, in order to respect Decidim's original order. The reason is that within Decidim, these are two different templates that will grow the amount of information they display, and will not fit properly if we keep them in a single line. The 2 elements are as follows: 

the topbar of the application, contains the logo, the search field and the actions for the user: Login or Sign up when they are not logged, and when they are logged, the notifications, message tray + all the user menus. If the user is an admin it will display the "edit" icon:
![image](https://github.com/okfn-brasil/minutas/assets/8941178/168baf9f-8be8-4af7-9265-a94a673a1815)

The links section is the navbar. This bar is dinamically generated within the innards of decidim according to which modules are active. It currently only has "Inicio", "Processos" and "Ajuda", however, depending on the activity of your decidim it can grow to have 8 more options. If we were to put them within the same space if the topbar, the template would brake which is why we chose to play with both the design you gave us, and Decidim's template. Below is an example of what a full navbar would look like with Decidim's natural template:

![image](https://github.com/okfn-brasil/minutas/assets/8941178/5c8d9377-b578-4f7c-b7d8-462feaa5a960)

The only option we are missing is to add the link for Open Knowledge Brasil. For this we can decide whether to put iut on the top bar, which I would recommend so as to keep information hierarchy (topbar for general site info, navbar for anything related to minutas portal)

**Comment by ghost** [comment]
_Intent: Add Link to Open Knowledge Brasil on the top bar (to the right of the logo)._

**Comment by ghost** [comment]
Screenshots after patch:

<table style="width:100%">
  <tr>
    <td style="width:50%;">
      <img width="1424" src="https://github.com/okfn-brasil/minutas/assets/141537607/51681b07-a4ca-4cb7-b33f-34ed75d0b407" alt="home">
    </td>
    <td style="width:50%;">
      <img width="1424"  src="https://github.com/okfn-brasil/minutas/assets/141537607/d744dd13-98b7-4ab7-8913-9651814134fb" alt="click">
    </td>
  </tr>
</table>
